name: Build and Deploy JAR

on:
  push:
    branches:
      - main   # Trigger the action when code is pushed to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'  # Use AdoptOpenJDK distribution, you can change it to 'zulu' or 'temurin' as needed
          java-version: '11'

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: jar-file
          path: build/libs/*.jar  # Adjust based on the path to your built JAR

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download JAR artifact
        uses: actions/download-artifact@v3
        with:
          name: jar-file

      - name: Copy JAR to Server
        run: scp -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa build/libs/*.jar user@<server-ip>:/path/to/deploy/
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
